apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app:  backend-service
    component: backend-service
    environment: development 
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - name: backend-service-ports
    port: 8090
    targetPort: 8090