apiVersion: v1
kind: Service
metadata:
  name: ckad-backend-service
  namespace: ckad
spec:
  type: NodePort
  selector:
    app: ckad-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000